### ISSUE TITLE
Please release the action with Node 20

### ISSUE THREAD

**Issue by sblantipodi** [benday-inc/set-property-value-in-appsettings#423]
Node 16 is deprecated. 
Please release the new version with Node 20 support. :)

Thanks

**Comment by benday** [comment]
@sblantipodi -- that was done and released about a month ago.  

https://github.com/benday-inc/set-property-value-in-appsettings/releases/tag/v1.5

Let me know if you're still having problems.

-Ben

**Comment by sblantipodi** [comment]
@benday I'm using 1.5 but GitHub still complain about NodeJS 16.

![image](https://github.com/benday-inc/set-property-value-in-appsettings/assets/4722227/3a03cb83-168d-4e82-b447-bcddab3348a8)

**Comment by benday** [comment]
@sblantipodi -- just pushed v1.6. Give it a shot and tell me if you're still getting the warning

**Comment by sblantipodi** [comment]
@benday it works now, thanks!
